### ISSUE TITLE
Consider adding a Cloud Bioinformatics Section

### ISSUE THREAD

**Issue by lynnlangit** [BioinformaNicks/Bioinformatics-training-collection#1]
I have several open source resources, including ['gcp-for-bioinformatics'](https://github.com/lynnlangit/gcp-for-bioinformatics) and ['public-cloud-genomics'](https://github.com/lynnlangit/TeamTeri/tree/master/5_Public_Cloud_Genomics) that you might want to link here.

**Comment by BioinformaNicks** [comment]
Will put your resources in there!

Thanks for the suggestion!
