### ISSUE TITLE
mRNAseq/Chipseq materials

### ISSUE THREAD

**Issue by joowkim** [BioinformaNicks/Bioinformatics-training-collection#4]
Hi @BioinformaNicks,

Hope you are doing well. I found these materials pretty helpful.

[https://hbctraining.github.io/main/](https://hbctraining.github.io/main/) by Harvard Chan Bioinformatics Core

Take care!

**Comment by BioinformaNicks** [comment]
Hi @heyyyjude, doing well indeed. How are you?

I'll add these, thanks a lot!
